### ISSUE TITLE
networkQuality -v -I en0, en7 (returns error)

### ISSUE THREAD

**Issue by careyjames** [network-quality/server#16]
networkQuality -v -I en0, en7                                                                                         
could not initialize NetworkQualityExecutions

is there a specific format for doing two interfaces ?

networkQuality -vsI en0 en7
that did work without error but did not show results separate.

so the MAN page shows using commas to separate the interfaces, guessing that's wrong?

**Comment by cpaasch** [comment]
Only one interface can be specified. I think the manpage is clear on that:

```
networkQuality [-chsv] [-I interface] [-C configuration URL]
```
