### ISSUE TITLE
make large file error

### ISSUE THREAD

**Issue by SupaFlys** [network-quality/server#24]
When doing make to generate the large file on macOS 13.1 I get...
% make                               
seq  -f "x" -s '' 4294967296 > root/files/large
seq: invalid format string: `x'
make: *** [root/files/large] Error 1

on ubuntu 22.04.1 LTS..
% make
seq  -f "x" -s '' 4294967296 > root/files/large
seq: format ‘x’ has no % directive
make: *** [Makefile:6: root/files/large] Error 1

both of which generate a large file with size 0

maybe something simpler?

dd if=/dev/urandom of=root/files/large bs=64M count=128

**Comment by cpaasch** [comment]
@randall  - wanna take a look at this?
