### ISSUE TITLE
Man Page Additions - `error_code` and `error_domain`

### ISSUE THREAD

**Issue by DaveL17** [network-quality/server#30]
### COMPUTER OUTPUT FIELD DESCRIPTION

It's possible for the json payload to include error messages and -- when an error state exists -- the fields `error_code` and `error_domain` will be present. For example, if the tool is run with no network access, the tool will return error_code `-1009`. Suggest adding `error_code` and `error_domain` to the Computer Output Field Description so users can be aware those fields may be present.
```
{'end_date': '2024-03-15 14:48:51.565', 'error_code': -1009, 'error_domain': 'NSURLErrorDomain', 'os_version': 'Version 14.4 (Build 23E214)', 'other': {}, 'start_date': '2024-03-15 14:48:51.472'}
```

**Comment by hawkinsw** [comment]
@DaveL17 Sorry for the delay on your two issues! I am planning to fix them tonight!!

**Comment by DaveL17** [comment]
Absolutely no problem whatsoever!

Cheers.

**Comment by DaveL17** [comment]
The man page that ships with macOS 15.0.1 (Sequoia) shows that this change has been promulgated.
