### ISSUE TITLE
Should base-port be used in the config payload URLs? (large/small/slurp)

### ISSUE THREAD

**Issue by spm1001** [network-quality/server#5]
Trying to run the server purely within LAN environment (and huge fan of the whole networkQuality project btw)

Running `networkQuality -C https://my.domain.com:4043/config` on client machine fails when trying to access `https://my.domain.com/large`. The server is correctly serving at `https://my.domain.com:4043/large`, but puts `https://my.domain.com/large` in the config payload, so I'm wondering if 4043 (or whatever is chosen with `-base-port`) should be referenced in the config payload URLs generated by `networkqualityd`?

(The public version serves over port 443 I believe? `https://mensura.cdn-apple.com/api/v1/gm/large` is supplied in the payload at `https://mensura.cdn-apple.com/api/v1/gm/config`, and using `-base-port 443` on my local test server makes everything work correctly.)

Setup:
1. Running the `go` version of the server on Ubuntu 20 with letsencrypt certs, and with `my.domain.com` resolving to the local IP address of the server machine - `192.168.1.2` 

2. Invoking networkqualityd like this (`sudo` so it can see the certs) and local IP
```
$ sudo ./networkqualityd --cert-file /etc/letsencrypt/live/my.domain.com/fullchain.pem --key-file /etc/letsencrypt/live/my.domain.com/privkey.pem --public-name my.domain.com -domain my.domain.com -listen-addr 192.168.1.2
2021/12/19 12:14:51 Network Quality URL: https://my.domain.com:4043/config
```
3. Running `networkQuality -C https://my.domain.com:4043/config` on the client machine returns

```
==== SUMMARY ====                                                                                         
Upload capacity: 0.000 bps
Download capacity: 0.000 bps
Upload flows: 0
Download flows: 0
Responsiveness: Low (0 RPM)
Error: Error Domain=NSURLErrorDomain Code=-1004 "Could not connect to the server." UserInfo={_kCFStreamErrorCodeKey=61, NSUnderlyingError=0x600001f25a40 {Error Domain=kCFErrorDomainCFNetwork Code=-1004 "(null)" UserInfo={_NSURLErrorNWPathKey=satisfied (Path is satisfied), interface: en0, ipv4, ipv6, dns, _kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <3A32613B-AD13-432A-BD6F-9087AE607060>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <3A32613B-AD13-432A-BD6F-9087AE607060>.<1>"
), NSLocalizedDescription=**Could not connect to the server., NSErrorFailingURLStringKey=https://my.domain.com/large**, NSErrorFailingURLKey=https://my.domain.com/large, _kCFStreamErrorDomainKey=1}
```

4. Adding `-base-port 443` to the server command at 2 makes the command on client at 3 run correctly  returning as follows:
```
==== SUMMARY ====                                                                                         
Upload capacity: 359.871 Mbps
Download capacity: 437.361 Mbps
Upload flows: 12
Download flows: 20
Responsiveness: High (2394 RPM)
```

**Comment by rafael-palacios** [comment]
can you explain how to use "-base-port 443" ?

**Comment by randall** [comment]
Apologies for the delay here, there were definitely some issues around base-port/config-port. PRs #13 and #14 cleaned up the usage/consistency.

**Comment by randall** [comment]
FWIWI: I am renaming `-config-port` to `-public-port` in #23
