### ISSUE TITLE
open source client implementation ?

### ISSUE THREAD

**Issue by aglossa** [network-quality/server#7]
As there is a RFC and a Golang server implementation of the test protocol, is there any hope that Apple or community will release a FOSS alternative to networkQuality on macOS ?

Context : target usage is to incorporate the test in our organisation monitoring (25000 users with the corresponding WLAN / LAN)

**Comment by richb-hanover** [comment]
A partial answer: check out https://github.com/network-quality/goresponsiveness that contains a Go implementation of the client, as well as a Dockerfile

**Comment by hawkinsw** [comment]
> As there is a RFC and a Golang server implementation of the test protocol, is there any hope that Apple or community will release a FOSS alternative to networkQuality on macOS ?
> 
> Context : target usage is to incorporate the test in our organisation monitoring (25000 users with the corresponding WLAN / LAN)

@aglossa Were you able to find the go implementation that is now hosted in this organization?

**Comment by aglossa** [comment]
I first tried the client with Apple public servers. As the results were not comparable with Apple networkQuality cli, I paused my experimentations and followed the dev. As I understand them, there is progress to understand the Apple metrics and I will return to my tests in the next month.
Kind regards.

**Comment by hawkinsw** [comment]
Great!! I am working actively on the open-source client, so please keep me
posted! If you have bug reports I will absolutely act on them quickly!

**Comment by randall** [comment]
@aglossa If you still seeing issues with the Apple public servers, using the Apple networkQuality client, please open an issue via https://support.apple.com/guide/feedback-assistant/get-started-fbab81460adb/mac

iI you are experiencing issues with the Apple public servers using goresponsiveness, please file an issue @ https://github.com/network-quality/goresponsiveness 

Thank you!
